# -*- coding: utf-8 -*-
"""Copy of Groq_Chat_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTsd2eSporeBCIex4CuiNHgn8-q3ZNH_

#Install Packages
"""

pip install groq

pip install gradio

"""# Import the Packages"""

import gradio
from groq import Groq

"""Add your api key here"""

client = Groq(
    api_key="",
)

"""#Define a function to give content and role"""

def initialize_messages():
    return [{"role": "system",
             "content": "You are a skilled career advisor with a successful track record with years of experience. Your role is to assist people by providing guidance to choose there career paths and courses in a  professional manner.Dont respond to unrelated querry"}]

"""#Assign it to a variable"""

messages_prmt = initialize_messages()

print(messages_prmt)

[{},{}]

"""#Define a function to connect with LLM"""

def customLLMBot(user_input, history):
    global messages_prmt

    messages_prmt.append({"role": "user", "content": user_input})

    response = client.chat.completions.create(
        messages=messages_prmt,
        model="llama3-8b-8192",
    )
    print(response)
    LLM_reply = response.choices[0].message.content
    messages_prmt.append({"role": "assistant", "content": LLM_reply})

    return LLM_reply

"""#Create an object of chat interface class in gradio"""

import gradio.themes.base as base

theme = base.Base(primary_hue="blue", secondary_hue="violet")
iface = gradio.ChatInterface(customLLMBot,
                     chatbot=gradio.Chatbot(height=300),
                     textbox=gradio.Textbox(placeholder="Ask me a question related to your career"),
                     title="Career Advisor ChatBot",
                     description="Chat bot for career advise",
                     theme=theme,
                     examples=["hi","what are diffrent career path in cyber security","which is the most promising career path", "what are diffrent career path in ai"],
                     submit_btn=True
                     )

"""#Call launch function to execute"""

iface.launch(share=True)